### ISSUE TITLE
which property is verified on ACASXU_2_9?

### ISSUE THREAD

**Issue by dgl-prc** [jjgold012/MinimalDNNModificationLpar2020#1]
Hi, 
I found the default model used in  SATexample.py is ACASXU_2_9, and according to the paper [Reluplex](https://arxiv.org/abs/1702.01135),  ACASXU_2_9 is tested on three properties: property 1,  property 2, and property 8.
However, none of these properties require that output "strong left" (output[3], 0-index) is minimal and the input constraints also belong to none of them (if I have the right understanding of the code.).  

So my question is which property is verified on ACASXU_2_9?

https://github.com/jjgold012/MinimalDNNModificationLpar2020/blob/1c967dbdbf2dc7facafbdbb03c96f0bce6f3b78b/NetworkCorrection/SATexample.py#L9

https://github.com/jjgold012/MinimalDNNModificationLpar2020/blob/1c967dbdbf2dc7facafbdbb03c96f0bce6f3b78b/NetworkCorrection/SATexample.py#L25-L42

**Comment by jjgold012** [comment]
If I'm not mistaken the property being verified is part of property 8, meaning that the minimal output in neither 0 or 1 (in this case searching specifically for minimal output 3). In any case this property was given to me by @guykatzz, so it is better to ask him.

**Comment by guykatzz** [comment]
Ben's answer is correct, as far as I remember. The numerical values you see as the bounds are after the ACAS Xu normalization process.

**Comment by dgl-prc** [comment]
Thanks for your response, but I'm still a bit confused about the two points (but this does not hurt the effectiveness of this work and prevent this work from being very interesting and valuable).

First, according to the paper [Reluplex](https://arxiv.org/pdf/1702.01135.pdf) (Page 30), the input constraints of property 8 are described as follows:
> [0.0, 60760.0]
[-3.141592, -2.356194]
[-0.1, 0.1]
[600.0, 1200.0]
[600.0, 1200.0]

Note that the range of the second variable and the third variable is different, so their normalized values should be different as well (if they use the same normalization parameters)?

Second,   according to the paper Reluplex, the desired output property of property 8 is depicted as follows:

> Desired output property: the score for “weak left” is minimal or the score
for COC is minimal.

This seems to mean that the minimal output is **either** 0 or 1?

**Comment by guykatzz** [comment]
Hi,
The exact normalization process can be found as part of the Reluplex code - it uses parameters stored in the nnet file itself.

Yes, the minimal value needs to be either 0 or 1, so the negation of this property is that the minimal value is either 2, 3 or 4. So, if we can find a case where the 3rd output is minimal, we have found a counter example for the original property.

**Comment by dgl-prc** [comment]
Thanks for your response. I see
